dist: trusty
sudo: required

env:
  - COREOS_TRACK=beta

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/current/version.txt -o version.txt
  - export $(cat version.txt | xargs)

script:
  - curl -L https://${COREOS_TRACK}.release.core-os.net/amd64-usr/${COREOS_VERSION}/coreos_developer_container.bin.bz2 -o coreos_developer_container.bin.bz2
  - bunzip2 -k coreos_developer_container.bin.bz2
  - mkdir ${COREOS_VERSION}
  - sudo mount -o ro,loop,offset=2097152 coreos_developer_container.bin ${COREOS_VERSION}
  - sudo tar -cp --one-file-system -C ${COREOS_VERSION} . | docker import - ${DOCKER_USERNAME}/coreos-developer:${COREOS_VERSION}

after_success:
  - docker push ${DOCKER_USERNAME}/coreos-developer:${COREOS_VERSION}
